export const VIEW_ACTIVITY = 'VIEW_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_WITH_USER = 'UPDATE_ACTIVITY_WITH_USER';
export const UPDATE_USER_WITH_LIFE = 'UPDATE_USER_WITH_LIFE';
export const UPDATE_USER_WITH_ATTACK = 'UPDATE_USER_WITH_ATTACK';
export const UPDATE_USER_WITH_DEFENCE = 'UPDATE_USER_WITH_DEFENCE';