export const LOAD_MONSTERS = 'LOAD_MONSTERS';
export const SHOW_PAYMENT = 'SHOW_PAYMENT';
export const SET_RANKING = 'SET_RANKING';
export const SET_TARGET_MONSTER = 'SET_TARGET_MONSTER';
export const SET_TELEGRAM_CONFIG = 'SET_TELEGRAM_CONFIG';
export const SET_API_TOKEN = 'SET_API_TOKEN';