export const characters = [
    {
        id: 1,
        name: 'man1',
        imageSrc: '/assets/character/man1.png',
        price: 1200,
        energy: 1200,
        attack: 10,
        defence: 5,
        imageAlt: "This is item1",
        isLock: true,
    },
    {
        id: 2,
        name: 'man2',
        imageSrc: '/assets/character/man2.png',
        price: 1500,
        energy: 1500,
        attack: 15,
        defence: 3,
        imageAlt: "This is item1",
        isLock: true,
    },
    {
        id: 3,
        name: 'man1',
        imageSrc: '/assets/character/man3.png',
        price: 1200,
        energy: 1200,
        attack: 10,
        defence: 5,
        imageAlt: "This is item1",
        isLock: true,
    },
    {
        id: 4,
        name: 'man2',
        imageSrc: '/assets/character/man4.png',
        price: 1500,
        energy: 1500,
        attack: 15,
        defence: 3,
        imageAlt: "This is item1",
        isLock: true,
    },
]