export const items = [
    {
        id: 1,
        name: 'item1',
        imageSrc: '/assets/shop/item_axe.png',
        level: 1,
        price: 200,
        attribute: 5,
        type: "attack",
        imageAlt: "This is item1",
        buy: true,
    },
    {
        id: 2,
        name: 'item2',
        imageSrc: '/assets/shop/item_bow.png',
        level: 2,
        price: 800,
        attribute: 10,
        type: "attack",
        imageAlt: "This is item2",
        buy: true,
    },
    {
        id: 3,
        name: 'item3',
        imageSrc: '/assets/shop/item_dagger.png',
        level: 3,
        price: 1000,
        attribute: 15,
        type: "attack",
        imageAlt: "This is item3",
        buy: false,
    },
    {
        id: 4,
        name: 'item4',
        imageSrc: '/assets/shop/item_mace.png',
        level: 4,
        price: 1200,
        attribute: 20,
        type: "attack",
        imageAlt: "This is item4",
        buy: false,
    },
    {
        id: 5,
        name: 'item5',
        imageSrc: '/assets/shop/item_shield2.png',
        level: 1,
        price: 150,
        attribute: 3,
        type: "defence",
        imageAlt: "This is item5",
        buy: false,
    },
    {
        id: 6,
        name: 'item6',
        level: 2,
        price: 700,
        attribute: 12,
        type: "defence",
        imageSrc: '/assets/shop/item_shield1.png',
        imageAlt: "This is item6",
        buy: false,
    },
    {
        id: 7,
        name: 'item7',
        level: 2,
        price: 500,
        attribute: 8,
        type: "defence",
        imageSrc: '/assets/shop/item_shield3.png',
        imageAlt: "This is item7",
        buy: true,
    },
    {
        id: 8,
        name: 'item8',
        level: 2,
        price: 600,
        attribute: 10,
        type: "defence",
        imageSrc: '/assets/shop/item_shield4.png',
        imageAlt: "This is item8",
        buy: false,
    },
    {
        id: 9,
        name: 'item9',
        level: 3,
        price: 700,
        attribute: 15,
        type: "attack",
        imageSrc: '/assets/shop/item_spear.png',
        imageAlt: "This is item9",
        buy: false,
    },
    {
        id: 10,
        name: 'item10',
        level: 3,
        price: 700,
        attribute: 15,
        type: "defence",
        imageSrc: '/assets/shop/item_shield4.png',
        imageAlt: "This is item10",
        buy: true,
    },
    {
        id: 11,
        name: 'item11',
        level: 4,
        price: 800,
        attribute: 20,
        type: "attack",
        imageSrc: '/assets/shop/item_spear.png',
        imageAlt: "This is item11",
        buy: false,
    },
]